# Generated by Django 5.0.2 on 2024-02-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=50)),
                ('area_status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='active', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('camera_name', models.CharField(max_length=70)),
                ('camera_status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='active', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('city_status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='active', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='MappedTable',
            fields=[
                ('map_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('final_status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='active', max_length=8)),
                ('area_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.area')),
                ('camera_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.camera')),
                ('city_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city')),
            ],
        ),
    ]
