# Generated by Django 5.0.2 on 2024-02-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappedtable',
            name='final_status',
        ),
        migrations.AddField(
            model_name='mappedtable',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='mappedtable',
            name='map_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
